CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    deal_id TEXT,
    finance_name TEXT,
    deal_converted_date DATE,
    ntp_received_date DATE, 
    install_completed_on DATE, 
    stage TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);  