CREATE TABLE IF NOT EXISTS deal_info (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_type TEXT,
    stage TEXT, 
    job_number TEXT, 
    deal_name TEXT,
    deal_ready_date DATE,
    deal_converted_date DATE,
    welcome_call_date DATE,
    completed_date DATE,
    closing_date DATE,
    project_coordinator TEXT
);