CREATE TABLE IF NOT EXISTS contact (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company TEXT,
    first_name TEXT,
    last_name TEXT,
    phone VARCHAR(10),
    email TEXT,
    language_preferred TEXT,
    first_name_2 TEXT,
    last_name_2 TEXT,
    phone_2 VARCHAR(10),
    email_2 TEXT,
    email_opt_out TEXT
);