CREATE TABLE IF NOT EXISTS engineering (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    eng_status TEXT,
    site_plan_start_date DATE,
    site_plan_complete_date DATE,
    planset_start_date DATE,
    stamp_required TEXT,
    stamp_requested TEXT,
    stamp_received TEXT,
    ee_cf_package_required TEXT,
    ee_stamp_req_date TEXT,
    ee_stamp_rec_date TEXT,
    planset_complete TEXT,
    monitoring_complete TEXT,
    engineering_notes TEXT,
    m2_eng_complete_date TEXT
);