CREATE TABLE IF NOT EXISTS permit (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    permit_status TEXT,
    ahj TEXT,
    permit_number TEXT,
    package_start_date DATE,
    submitted_date DATE,
    received_date DATE,
    rejected_date DATE,
    pm_notes TEXT
);