CREATE TABLE IF NOT EXISTS installation (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    install_status TEXT,
    scheduled_on DATE,
    install_start_date DATE,
    completed_on DATE,
    footing_insp_req TEXT,
    footing_sch_on DATE,
    footing_inst_date DATE,
    footing_inst_comp_date DATE,
    footing_insp_sch_on DATE,
    footing_insp_date DATE,
    footing_insp_pass_date DATE,
    footing_insp_fail_date DATE
);