CREATE TABLE IF NOT EXISTS hoa_info (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hoa_info_status TEXT,
    hoa_start_date DATE,
    package_ready TEXT,
    package_submitted TEXT,
    package_received TEXT,
    hoa_submitted_date DATE,
    hoa_approved_date DATE,
    hoa_rejected_date DATE
);