CREATE TABLE IF NOT EXISTS counters (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    site_survey INTEGER,
    pre_engineering INTEGER,
    contracts INTEGER,
    engineering INTEGER,
    hoa INTEGER,
    permitting INTEGER,
    pre_contstruction INTEGER,
    construction INTEGER,
    inspection INTEGER,
    pto INTEGER
);