CREATE TABLE IF NOT EXISTS materials (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    materials_status TEXT,
    order_start_date DATE,
    order_finish_date DATE,
    delivery_date DATE,
    received_on DATE,
    module_name TEXT,
    module_size TEXT,
    num_of_modules INTEGER,
    system_size TEXT,
    inverter_type TEXT,
    inverter_name TEXT,
    num_of_inverters INTEGER,
    additional_items TEXT,
    notes TEXT
);