ALTER TABLE IF EXISTS projects
  ADD COLUMN IF NOT EXISTS rea_id INTEGER REFERENCES rea(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS deal_info
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS contact
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS deal_address
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS rea
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS lead_source
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS engineering
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS milestones
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS site_survey
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS site_survey
  ADD COLUMN IF NOT EXISTS surveyor_id INTEGER REFERENCES employees(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS contract
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS finance
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS employees
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS hoa
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS permit
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS materials
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS installation
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS installation
  ADD COLUMN IF NOT EXISTS crew_lead_id INTEGER REFERENCES employees(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS hoa_info
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS pto
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS counters
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS inspection
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS company
  ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE;