ALTER TABLE IF EXISTS projects
  DROP COLUMN IF EXISTS rea_id;

ALTER TABLE IF EXISTS deal_info
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS contact
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS deal_address
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS rea
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS lead_source
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS engineering
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS milestones
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS site_survey
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS site_survey
  DROP COLUMN IF EXISTS surveyor_id;

ALTER TABLE IF EXISTS contract
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS finance
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS employees
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS hoa
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS permit
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS materials
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS installation
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS installation
  DROP COLUMN IF EXISTS crew_lead_id;

ALTER TABLE IF EXISTS hoa_info
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS pto
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS counters
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS inspection
  DROP COLUMN IF EXISTS project_id;

ALTER TABLE IF EXISTS company
  DROP COLUMN IF EXISTS project_id;