[
    {
        On_Hold_Notes: 'missing usage.',
        Owner: {
            name: 'Grover Richardson',
            id: '2731480000010676001',
            email: 'grichardson@americansolaradvantage.com',
        },
        COMMISSION_STATUS: null,
        Permitting_Notes: null,
        Footing_Inspection_Passed_Date: null,
        Final_Payment_Received: null,
        Completed_Date: null,
        Contract_Sent_Date: null,
        Expected_Delivery_Date: null,
        Crew_Lead: 'Grover',
        PTO_Failed_Date: null,
        Job_Number: 1134,
        Yr_19_Estimated_Production: null,
        $process_flow: false,
        HOA_Package_Received_From_Advisor: null,
        Notice_to_Proceed_Requested_Date_PACE: null,
        Stage: 'Closed Lost',
        Street: '944 Enrique Ridge',
        M3_Submitted: null,
        HDM_M1_Submitted_Date: null,
        $approval: {
            delegate: false,
            approve: false,
            reject: false,
            resubmit: false,
        },
        CUSTOMER_CASHBACK_STATUS: null,
        HOA_1_CITY: null,
        Monitoring_Complete: true,
        Finance_Status1: 'Not Started',
        HOA_Status1: 'REQUIRED',
        Structural_Stamp_Requested_date: null,
        Permit_Package_Rejected_Date: null,
        Footing_Inspection_Scheduled_On: null,
        Yr_20_Estimated_Production: null,
        HOA_2_NAME: null,
        HDM_M2_Submitted_Date: null,
        Permit_Package_Start_Date: null,
        HOA_Start_Date: null,
        M2_Submitted: null,
        HOA_2_COMPANY: null,
        HOA_2_ZIP: null,
        Engineering_Current_Status: null,
        rd_Party_job_number: null,
        Phone_2: null,
        REFERRAL_STATUS: null,
        Engineering_Notes: null,
        Deal_Ready_Date: null,
        Yr_1_Production_Guarantee: 'FZF',
        HOA_2_STATE: null,
        HOA_Approved: null,
        $review_process: {
            approve: false,
            reject: false,
            resubmit: false,
        },
        Preliminary_NTP_Approval_Date: null,
        M3_Payment_Requested: null,
        HDM_M2_Approval_Date: null,
        SYSTEM_SIZE_KW1: 5.85,
        Completed_Date1: null,
        M1_Submitted: null,
        M2_Approval_Date1: null,
        Sales: null,
        PTO_STATUS: 'PTO Approved',
        Yr_22_Estimated_Production: null,
        Materials_Received_On: null,
        Credit_Score: null,
        Finance_Type1: 'PRE-PAID PPA',
        KWH: null,
        Source_Name: null,
        Permit_Recieved: null,
        PTO_Start_Date: null,
        HOA_1_STATE: null,
        $orchestration: false,
        REA: {
            name: 'Grover Richardson',
            id: '2731480000007948001',
        },
        Contact_Name: null,
        HOA_STATUS: 'REQUIRED',
        Layout: {
            name: 'ASA LAYOUT',
            id: '2731480000004425001',
        },
        HOA_Package_Ready_for_Advisor: null,
        REA_EMAIL: 'grichardson@asa.solar',
        Yr_21_Estimated_Production: null,
        Lead_Source: null,
        Site_Surveyor: {
            name: 'Bryan Sos',
            id: '2731480000006790135',
        },
        M4_Payment_Received_Date: null,
        Footing_Inspection_Date: null,
        Yr_24_Estimated_Production: null,
        $currency_symbol: '$',
        REA_Signed_FSP_Date: null,
        EXTENSIVE_ADDERS_AMOUNT: null,
        REA_PHONE: '951-833-8143',
        Module_Name1: {
            name: 'CSUN - 390-72MH',
            id: '2731480000015940047',
        },
        M3_Payment_Received: null,
        Last_Activity_Time: '2020-07-27T15:12:41-07:00',
        System_Type: 'Residential',
        Show_Production_Info: true,
        ENGINEERING_STATUS: null,
        Yr_8_Estimated_Production: null,
        Finance_Account_Created_Date: null,
        System_Size_kW: null,
        Yr_15_Estimated_Production: null,
        Deal_Name: 'Test Deal Do-Not-Touch',
        M1_Payment_Requested: null,
        Zip_Code: '92508',
        $approved: true,
        CONTRACT_AMOUNT: null,
        MODULE_NAME: null,
        HOA_1_ZIP: null,
        AHJ_Verified: false,
        New_Contract_Req: false,
        Meter_spot_requested: null,
        Off_Hold_Date: null,
        Source_Email: null,
        HDM_M1_Approval_Date: null,
        On_Hold_Date: '2020-07-21T15:00:00-07:00',
        Date_Converterd: '2020-06-16',
        State: 'CA',
        HOA_Rejected_Date: null,
        Site_Survey_Completed: null,
        Yr_12_Estimated_Production: null,
        Yr_6_Estimated_Production: null,
        Inspection_Date: '2020-06-16',
        Source_Phone1: null,
        Closing_Date: null,
        Job_Number_New: null,
        MPU_Completed: null,
        HOA_Submitted: null,
        PTO_Issued: null,
        HOA_1_STREET: null,
        Escalator: null,
        Modified_By: {
            name: 'Bobby Harris',
            id: '2731480000000125009',
            email: 'bharris@asa.solar',
        },
        $review: null,
        Notes1: null,
        Additional_Items: [],
        CUSTOMER_CASHBACK_AMOUNT: null,
        Yr_17_Estimated_Production: null,
        Modified_Time: '2020-07-27T15:12:40-07:00',
        Inspection_Approved_Date: null,
        Finance_Status: 'Not Started',
        REFERRAL_AMOUNT1: null,
        OPERATION_STATU: 'Installation completed',
        Structural_Stamp_Received_date: null,
        Operation_Status: 'Installation completed',
        PERMIT_STATUS: 'Permit Package Received',
        $in_merge: false,
        $approval_state: 'approved',
        Contract_Executed: null,
        Next_Steps: null,
        Site_Surveyor_Status: 'Site Survey Completed',
        Payment_Requested: null,
        INVERTER_NAME: null,
        AHJ: {
            name: 'California Department of Housing & Community Development',
            id: '2731480000011391057',
        },
        Site_Plan_Start_Date: null,
        Placard_Ordered: false,
        Electrical_Engineering_Package_Required: null,
        HOA_Approved_Date: null,
        Permit_Status1: 'Permit Package Received',
        Inspection_Scheduled_On: null,
        M4_Payment_Requested_Date: null,
        Yr_4_Estimated_Production: null,
        AHJ_Structural_Stamp_Test: 'Yes',
        MPU_start_date: null,
        Planset_Complete: null,
        HOA_2_CITY: null,
        Yr_3_Estimated_Production: null,
        $state: 'save',
        Placard_Received: false,
        id: '2731480000015233052',
        Par_Price: null,
        Yr_10_Estimated_Production: null,
        Source_Phone: null,
        Created_Time: '2020-06-15T09:34:55-07:00',
        Site_Survey_Status1: 'Site Survey Completed',
        Project_Coordinator: {
            name: 'Grover Richardson',
            id: '2731480000010676001',
        },
        Yr_5_Estimated_Production: null,
        PTO_Submitted: null,
        HOA_1_PHONE: null,
        Yr_2_Estimated_Production: 'SFGSFG',
        Created_By: {
            name: 'Grover Richardson',
            id: '2731480000010676001',
            email: 'grichardson@americansolaradvantage.com',
        },
        NUM_OF_MODULES: 15,
        Meter_spot_completed: null,
        Description: null,
        Planset_Start_Date: null,
        Contract_Statuss: null,
        Material_Order_Finish_Date: null,
        CASH_BACK_PROMO: null,
        Inspection_Failed_Date: null,
        HOA_2_STREET: null,
        MODULE_SIZE_W: 390,
        Lead_Conversion_Time: null,
        HOA_2_PHONE: null,
        Overall_Sales_Duration: null,
        Email_Opt_Out: false,
        Crew_Lead_Phone: null,
        HOA_Submitted_Date: null,
        Amount: null,
        Finance_Notes: null,
        Footing_Inspection_Failed_Date: null,
        Footing_Inspcetion_Required: 'Yes',
        COMMISSION: null,
        Yr_14_Estimated_Production: null,
        HOA_1_COMPANY: null,
        Notice_to_Proceed_Received_Date_PACE: null,
        Permit_Submitted: null,
        Tag: [],
        Site_Survey_Scheduled_On: null,
        M2_Payment_Received: null,
        Permit_Number: null,
        MPU_quote_requested: null,
        Company: null,
        Footing_Install_Date: null,
        M3_Approval_Date1: null,
        PTO_Status1: 'PTO Approved',
        Structural_Stamp_Received_Date1: null,
        Footing_Install_Complete_Date: null,
        $followers: null,
        Contract_Status: null,
        Souce_Email: null,
        Inverter_Name1: {
            name: 'SOLAREDGE SE6000-US',
            id: '2731480000015922052',
        },
        NUM_OF_INVERTERS: 1,
        Production_Guarantee_Yrs: '25 Years',
        MPU_needed: false,
        Site_Survey_Scheduled_For1: null,
        $followed: false,
        M1_5_Submitted_Date: null,
        Milestone_Status: 'NTP Received',
        Yr_13_Estimated_Production: null,
        $editable: true,
        City: 'Riverside',
        REA_COMMISSION: null,
        M1_Payment_Received: null,
        Inverter_Type: 'SolarEdge',
        Utility_name: null,
        Material_Order_Start_Date: null,
        Language_Preferred: 'English Only',
        Gate_Code: null,
        Installation_Scheduled_For: '2020-06-16',
        M2_Payment_Requested: null,
        Yr_9_Estimated_Production: null,
        Yr_23_Estimated_Production: null,
        Email_2: null,
        FSP_Executed_Date: null,
        Yr_16_Estimated_Production: null,
        Welcome_Call_Date: null,
        System_Info_Status: 'Incomplete',
        M1_5_Approval_Date: null,
        HOA_1_NAME: null,
        Site_Surveyor_Phone: null,
        First_Name_2: null,
        HOA_1_EMAIL: null,
        Milestone_Notes: null,
        Install_Scheduled_On: null,
        HOA_Package_Submitted_To_Advisor: null,
        First_Name: 'John',
        AHJ_Requirements: null,
        Last_Name_2: null,
        Phone: '907-341-5162',
        Inspection_Notes: null,
        Email1: 'groverrichardson1987@gmail.com',
        Finance_Type: 'HDM/CASH',
        HDM_Payment_Requested: null,
        Site_Layout_Complete_Date: null,
        Yr_25_Estimated_Production: null,
        M1_Approval_Date: null,
        Footing_Install_Scheduled_On: null,
        Sales_Cycle_Duration: null,
        Last_Name: 'Doe',
        Inspection_Status: 'Approved',
        Job_Number1: null,
        Yr_18_Estimated_Production: null,
        Yr_7_Estimated_Production: null,
        HOA_2_EMAIL: null,
        Yr_11_Estimated_Production: null,
    },
];
